Added --url-parse param to parse and print url

diff --git a/.local/bin/work/dbi b/.local/bin/work/dbi
--- a/.local/bin/work/dbi
+++ b/.local/bin/work/dbi
@@ -115,6 +115,12 @@ case $COMMAND in
         echo $URL
         exit
         ;;
+    "--url-parse")
+        URL=$(getDatabaseUrl)
+        [[ -z $URL ]] && echo "Invalid or unsupported [SERVICE]" && exit 1
+        echo $URL
+        exit
+        ;;
     *)
         help
         exit 1
