Removed unnecessary complexity and added sane defaults

diff --git a/.local/bin/work/dbi b/.local/bin/work/dbi
--- a/.local/bin/work/dbi
+++ b/.local/bin/work/dbi
@@ -1,4 +1,5 @@
 #!/usr/bin/zsh
+
 SERVICE=$1
 ENVIRONMENT=$2
 
@@ -21,81 +22,42 @@ RAW_DATA=$(arthur param read $SERVICE $ENVIRONMENT)
 
 [[ -z $RAW_DATA ]] && echo "Invalid [SERVICE]" && exit 1
 
-ENV_KEY_MAP_FILE=~/.cache/dbi/$SERVICE.$ENVIRONMENT
-
-if [[ ! -e $ENV_KEY_MAP_FILE ]]; then
-    # See if service has configured an database url
-    DB_URL=$(echo $RAW_DATA | grep -o "DB_URL.*\|DATABASE_URL.*" | sed 's/^[^=]*=//' | tr -d '"')
-
-    if [[ ! -z $DB_URL ]]; then
-        echo "Service has database url configured, no mapping needed"
-        echo "Trying to connect..."
-        psql $DB_URL
-        exit
-    fi
-
-    echo "First time connecting to $SERVICE.$ENVIRONMENT, trying to create variable mapping"
-    DB_VARS=($(echo $RAW_DATA | grep -o "DB_.*\|DATABASE_.*"))
-    DB_VAR_KEYS=()
-    for db_var in "${DB_VARS[@]}"
-    do
-        key_value=($(echo "$db_var" | tr '=' '\n'))
-        DB_VAR_KEYS=(${DB_VAR_KEYS[@]} ${key_value[1]})
-    done
-
-    host=
-    port=
-    user=
-    pass=
-    db=
-
-    for var in "${DB_VAR_KEYS[@]}"
-    do
-        [[ $var =~ "HOST" ]] && host=$var
-        [[ $var =~ "PORT" ]] && port=$var
-        [[ $var =~ "USER" ]] && user=$var
-        [[ $var =~ "PASS" ]] && pass=$var
-        [[ $var =~ "NAME" ]] && db=$var
-    done
-
-    keys=($host $port $user $pass $db)
-
-    [[ ${#keys} -ne 5 ]] && \
-        echo "Failed to create variable mapping. Unsupported service" && \
-        exit 1
-
-    [[ ! -d ~/.cache/dbi ]] && mkdir ~/.cache/dbi
-
-    echo $keys > ~/.cache/dbi/$SERVICE.$ENVIRONMENT && \
-        echo "Local cache for $SERVICE.$ENVIRONMENT created."
+# Try and connect via database url, as this is the easiest method
+DB_URL=$(echo $RAW_DATA | grep -o "DB_URL.*\|DATABASE_URL.*" | sed 's/^[^=]*=//' | tr -d '"')
+if [[ ! -z $DB_URL ]]; then
+    echo "Trying to connect..."
+    psql $DB_URL
+    exit
 fi
 
-key_map=($(cat $ENV_KEY_MAP_FILE))
-index=1
-for key in "${key_map[@]}"
-do
-    value=$(echo $RAW_DATA | grep -o "$key=.*" | cut -d'=' -f 2 | tr -d '"')
-    case $index in
-        1)
-            host=$value
-            ;;
-        2)
-            port=$value
-            ;;
-        3)
-            user=$value
-            ;;
-        4)
-            pass=$value
-            ;;
-        5)
-            db=$value
-            ;;
-    esac
+# Try and find each database variable, with defaults as fallback
+DB_VARS=($(echo $RAW_DATA | grep -o "DB_.*\|DATABASE_.*\|POSTGRES_.*"))
 
-    index=$((index+1))
+# Fallbacks
+host=
+port=5432
+user=
+pass=
+db="$(echo "$SERVICE" | tr '-' '_')_$ENVIRONMENT"
+
+for var in "${DB_VARS[@]}"
+do
+    key_value=($(echo "$var" | tr '=' '\n'))
+    key=${key_value[1]}
+    value=$(echo "${key_value[2]}" | tr -d '"')
+
+    [[ $key =~ "HOST" ]] && host=$value
+    [[ $key =~ "PORT" ]] && port=$value
+    [[ $key =~ "USER" ]] && user=$value
+    [[ $key =~ "PASS" ]] && pass=$value
+    [[ $key =~ "NAME" ]] && db=$value
 done
 
-echo "Make sure that you are connected to the correct VPN"
+values=($host $port $user $pass $db)
+
+[[ ${#values} -ne 5 ]] && \
+    echo "Failed to fetch required values, service unsupported" && \
+    exit 1
+
 echo "Trying to connect..."
 PGPASSWORD=$pass psql -h $host -p $port -U $user -d $db
